# This file is auto-generated by the Rivet (https://rivet.gg) build system.
# 
# Do not edit this file directly.

class_name RivetCurrency
## Currency
## 
## Track user balances and allow them to deposit and withdraw.

const _ApiResponse := preload("../client/response.gd")

var _client: RivetClient

func _init(client: RivetClient):
	self._client = client

## Fetch Balance by Token
func fetch_balance_by_token(body: Dictionary = {}) -> RivetRequest:
	return self._client.build_request(HTTPClient.METHOD_POST, "/modules/currency/scripts/fetch_balance_by_token/call", body)



