# This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
# 
# Do not edit this file directly.
#
# Generated at 2024-09-10T10:39:33.148Z

class_name RivetRateLimit
## Rate Limit
## 
## Prevent abuse by limiting request rate.

const _ApiResponse := preload("../client/response.gd")

var _client: RivetClient

func _init(client: RivetClient):
	self._client = client



