# This file is auto-generated by the Rivet (https://rivet.gg) build system.
# 
# Do not edit this file directly.

class_name RivetUsers
## Users
## 
## Identify and manage users.

const _ApiResponse := preload("../client/response.gd")

var _client: RivetClient

func _init(client: RivetClient):
	self._client = client

## Fetch User
func fetch(body: Dictionary = {}) -> RivetRequest:
	return self._client.build_request("users.fetch", HTTPClient.METHOD_POST, "/modules/users/scripts/fetch/call", body)

## Authenticate User Token
## 
## Validate a user token. Throws an error if the token is invalid.
func authenticate_token(body: Dictionary = {}) -> RivetRequest:
	return self._client.build_request("users.authenticate_token", HTTPClient.METHOD_POST, "/modules/users/scripts/authenticate_token/call", body)



