# This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
# 
# Do not edit this file directly.
#
# Generated at 2024-09-10T10:39:33.148Z

class_name RivetUsers
## Users
## 
## Identify and manage users.

const _ApiResponse := preload("../client/response.gd")

var _client: RivetClient

func _init(client: RivetClient):
	self._client = client

## Fetch User
func fetch(body: Dictionary = {}) -> RivetRequest:
	return self._client.build_request(HTTPClient.METHOD_POST, "/modules/users/scripts/fetch/call", body)

## Authenticate User Token
## 
## Validate a user token. Throws an error if the token is invalid.
func authenticate_token(body: Dictionary = {}) -> RivetRequest:
	return self._client.build_request(HTTPClient.METHOD_POST, "/modules/users/scripts/authenticate_token/call", body)



