# This file is auto-generated by the Rivet (https://rivet.gg) build system.
# 
# Do not edit this file directly.

class_name RivetLogger

static func log(args):
	print("[Rivet] ", args)

static func warning(args):
	print("[Rivet] ", args)
	push_warning("[Rivet] ", args)

static func error(args):
	print("[Rivet] ", args)
	push_error("[Rivet] ", args)

