# This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
# 
# Do not edit this file directly.
#
# Generated at 2024-09-10T10:39:33.147Z

class_name RivetLogger

static func log(args):
	print("[Rivet] ", args)

static func warning(args):
	print("[Rivet] ", args)
	push_warning("[Rivet] ", args)

static func error(args):
	print("[Rivet] ", args)
	push_error("[Rivet] ", args)

