# This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
# 
# Do not edit this file directly.
#
# Generated at 2024-07-18T01:11:34.894Z

class_name BackendRateLimit
## Rate Limit
## 
## Prevent abuse by limiting request rate.

const _ApiResponse := preload("../client/response.gd")

var _client: BackendClient

func _init(client: BackendClient):
	self._client = client



