# This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
# 
# Do not edit this file directly.
#
# Generated at 2024-07-18T01:11:34.893Z

class_name BackendUsers
## Users
## 
## Identify and manage users.

const _ApiResponse := preload("../client/response.gd")

var _client: BackendClient

func _init(client: BackendClient):
	self._client = client

## Fetch User
func fetch(body: Dictionary = {}) -> BackendRequest:
	return self._client.build_request(HTTPClient.METHOD_POST, "/modules/users/scripts/fetch/call", body)

## Authenticate User Token
## 
## Validate a user token. Throws an error if the token is invalid.
func authenticate_token(body: Dictionary = {}) -> BackendRequest:
	return self._client.build_request(HTTPClient.METHOD_POST, "/modules/users/scripts/authenticate_token/call", body)



