[package]
name = "rivet-plugin-godot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 'z'
lto = true
strip = true

[dependencies]
futures = "0.3"
global-error = {  git = "https://github.com/rivet-gg/rivet.git", rev = "22baf31efa3ffcdad65ecc72ce25425ab61b9c6f" }
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = ["serde", "experimental-threads"] }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.27", default-features = false, features = ["rt"] }
toolchain = { path = "../../../cli/rivet-toolchain", package = "rivet-toolchain" }
# toolchain = { git = "https://github.com/rivet-gg/cli.git", rev = "f2fde5227f4672e408e54d2f95d017a919f39b4b", package = "rivet-toolchain" }

