name: "Push to Godot Asset Store"
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish new version to Godot Asset Store

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Godot Asset Lib
        uses: deep-entertainment/godot-asset-lib-action@v0.4.0
        with:
          action: addEdit
          username: ${{ secrets.GODOT_ASSET_LIBRARY_USERNAME }}
          password: ${{ secrets.GODOT_ASSET_LIBRARY_PASSWORD }}
          assetId: 1881
          assetTemplate: .asset-template.json
          baseUrl: https://godotengine.org/asset-library/api
